### ISSUE TITLE
[DRIVER] Add an option to pre-load specified kernel module (specified by path to .ko file) before starting HyperHDR main daemon

### ISSUE THREAD

**Issue by S-trace** [webosbrew/hyperhdr-webos-loader#18]
Hi.

I have a TV which require to load specified driver (the sideloaded but working on the TV the ch341.ko in my case) to let wired LED controller to work on my TV.
Now I need to manually load the ch341.ko via SSH and then manually restart HyperHDR to make it work.

Is it possible to add an option to insmod the specified .ko module before starting HyperHDR main process?

Thanks.

**Comment by throwaway96** [comment]
You can create a script in `/var/lib/webosbrew/init.d` to load the kernel module at boot. Note that it must be executable, and its filename must comply with the requirements imposed by [`run-parts`](https://manpages.ubuntu.com/manpages/xenial/en/man8/run-parts.8.html).

**Comment by tuxuser** [comment]
yep, loading custom drivers shouldn't be the job of this loader application.
