### ISSUE TITLE
HyperHDR 20 rc WebOS .ipk

### ISSUE THREAD

**Issue by pho084** [webosbrew/hyperhdr-webos-loader#27]
[please delete this... wanted to post this on the official github...]

hi
first of all thanks for 20 rc!

can somebody provide an .ipk for the latest version?

it's not (yet) on https://github.com/webosbrew/hyperhdr-webos-loader

much appreciated

**Comment by throwaway96** [comment]
Uh, what "official github"?

Anyway... #28

**Comment by pho084** [comment]
thank you kindly for keeping up support

with official i meant the HyperHDR github

**Comment by throwaway96** [comment]
HyperHDR does not officially support webOS, so this repo is as official as it gets for HyperHDR on webOS.
