### ISSUE TITLE
Out of Date

### ISSUE THREAD

**Issue by martydingo** [webosbrew/hyperhdr-webos-loader#7]
Hiya there,

This is currently on v18 beta, and v19 beta is out.

is there plans to update or is this repository now archived?

**Comment by Xploder** [comment]
You can just build a current version of HyperHDR yourself with the instructions posted here and replace the files.

Here's a current version https://mega.nz/file/sJNyUKhA#CkQqOb4ud3Di56g1KwISIda9DpXvHKGLCROFOEjYZOs

You need to replace the hyperhdr folder in /media/developer/apps/usr/palm/services/org.webosbrew.hyperhdr.loader.service/

**Comment by Informatic** [comment]
Hey, I've fixed up the CI pipeline and there's a new testing build in "releases".

**Comment by martydingo** [comment]
> Hey, I've fixed up the CI pipeline and there's a new testing build in "releases".

I think you'll need to increment the version, as otherwise current homebrew package managers won't detect an update.

**Comment by tuxuser** [comment]
Feel free to bump the version @Informatic , thx

**Comment by martydingo** [comment]
That IPK does work, I can confirm this installs fine via webos-dev-manager.

**Comment by tuxuser** [comment]
New release should be up soon
