### ISSUE TITLE
Missing Options

### ISSUE THREAD

**Issue by enigmacarpc** [webosbrew/hyperhdr-webos-loader#8]
Hello just installed HyperHDR for WebOS I am having some issues with washed out colors and I seem to be missing the below options compared to similar Raspberry PI builds.

 1. No options for SK6812 as a controller option, I use updraw for wled 
 2. No HDR to SDR option. 
 3. No video capturing options such as letting the system know you have a SK6812 type LED strip to make up for the extra white LED.
 4. HDR global under remote control doesn't do anything

**Comment by tuxuser** [comment]
Hello @enigmacarpc 

Please ask these kind of questions in the Discord: https://discord.gg/xWqRVEm
