### ISSUE TITLE
USB serial support

### ISSUE THREAD

**Issue by alucryd** [webosbrew/hyperhdr-webos-loader#9]
Hi there, I have no idea where to ask so I'll take a shot here.

I'd like to use an ESP32 on my C9 flashed with https://github.com/awawa-dev/HyperSerialESP32, the device is detected according to dmesg and lsusb, but no serial interface shows up so it's not usable in hyperhdr.

Comparing to my PC, it would seem webos is lacking a ch341 kernel driver. Any idea how to get that one on webos?

**Comment by nurikk** [comment]
We might be able to compile this driver for tvos 

https://github.com/torvalds/linux/blob/master/drivers/usb/serial/ch341.c

**Comment by tuxuser** [comment]
Look for your TV on this site: http://opensource.lge.com/product/list?ctgr=005&subCtgr=006

Should contain toolchain + kernel src.
Then you can try to compile respective kernel module.

**Comment by asturel** [comment]
hellobox on discord already compiled ch341 driver for 4.4.84 kernel (32bit and 64bit) you can found it here:

https://discord.com/channels/407937994037919756/413498235307425802/1038261780058755143

https://discord.gg/nKQW6FPWeM

**Comment by alucryd** [comment]
Thank you all for your replies! In the meantime I got my hands on a different board with a CH9102F which is natively supported, but I'll keep these in mind in case I have another similar project. I guess this can be closed as solutions have been proposed.
